[package]
name = "bbs"
version = "0.1.0"
authors = ["The Hyperledger Ursa Contributors"]
edition = "2018"

[dependencies]
amcl_wrapper = { version = "0.3.5", default-features = false, features = ["bls381"] }
arrayref = "0.3.6"
failure = "0.1.7"
generic-array = "0.13.2"
hash2curve = { version = "0.0.4", features = ["bls"] }
hex = "0.4.2"
sha2 = "0.8"
serde = { version = "1.0.106", features = ["serde_derive"] }
serde_cbor = "0.11.1"
