name: Ursa CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  SODIUM_BUILD_STATIC: 1

jobs:
  Build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        workdir: [ ".", "./libursa" ]

    steps:
    - uses: actions/checkout@v2

    - name: Build
      working-directory: ${{ matrix.workdir }}
      run: cargo build --verbose
      if: always()

    - name: Format
      working-directory: ${{ matrix.workdir }}
      run: cargo fmt --all -- --check
      if: always()

    - name: Docs
      working-directory: ${{ matrix.workdir }}
      run: cargo doc --no-deps
      if: always()

    - name: Clippy
      working-directory: ${{ matrix.workdir }}
      run: cargo clippy --all -- -W clippy::not_unsafe_ptr_arg_deref -A clippy::many_single_char_names
      if: always()

    - name: Check
      working-directory: ${{ matrix.workdir }}
      run: cargo check
      if: always()

    - name: Tests
      working-directory: ${{ matrix.workdir }}
      run: cargo test --release
      if: always()

    - name: Audit
      working-directory: ${{ matrix.workdir }}
      run: cargo audit
      if: always()

# disabled in AZP
#
#  Portable:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Portable
#      run: cargo build --manifest-path=libzmix/Cargo.toml --no-default-features --features=portable
#
#  secp256k1:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: test secp256k1
#      run: cargo run --release --manifest-path=libursa/Cargo.toml --bin test_secp256k1 --features="benchmarksecp256k1"
#
#
#  ed25519:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: test ed25519
#      run: SODIUM_BUILD_STATIC=1 cargo run --release --manifest-path=libursa/Cargo.toml --bin test_ed25519 --features="benchmarked25519"
#
#
#  WASMPACK:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: WASM pack
#      run: |
#         wasm-pack build libursa -- --no-default-features --features=portable_wasm
#         wasm-pack build libzmix/bbs -- --no-default-features --features=wasm
#
#  Nightly:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Build ASM on nightly
#      run: |
#         curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
#         rustup toolchain install nightly
#         rustup default nightly
#         rustc --version
#         cargo build --manifest-path=libzmix/Cargo.toml --no-default-features --features=asm
